global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loans-servicing'
    static_configs:
      - targets: ['host.docker.internal:5232']

  - job_name: 'loans-schedules'
    static_configs:
      - targets: ['host.docker.internal:5264']
        
  - job_name: 'loans-contracts'
    static_configs:
      - targets: ['host.docker.internal:5182']
        
  - job_name: 'loans-indebtedness'
    static_configs:
      - targets: ['host.docker.internal:5205']
